services:

  pull_req:
    image: pull_req:latest
    build:
      context: service
      dockerfile: Dockerfile.pull_req
    container_name: pull_req
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./service/pull_req/config.yaml:/config.yaml
    environment:
      - PULL_REQ_ADDRESS=:8080
      - DB_ADDRESS=postgres://postgres:password@postgres:5432/pullreq
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pullreq
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  migrate:
    image: migrate/migrate:latest
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      -path=/migrations -database=postgres://postgres:password@postgres:5432/pullreq?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    restart: "no"

volumes:
  postgres:

